### ISSUE TITLE
Propose logo

### ISSUE THREAD

**Issue by dee-y** [zephyrplace/feedfast#1]
Hello @tiago-marques, i am a graphic designer. I would like to know if you would be interested in me making a logo for this project. If you would have me, i would make a logo for you, and it's free.

**Comment by tiago-marques** [comment]
Hi @dee-y!

That would be awesome! I'm waiting for your contribution and the new logo 👍

**Comment by dee-y** [comment]
Hello @tiago-marques here is the logo i designed, let me know if i need to make any adjustments and your color pick.
![feedfast 2-01](https://user-images.githubusercontent.com/36637989/41558635-4f13c898-7339-11e8-8e31-05c94e872bd4.png)

**Comment by tiago-marques** [comment]
WOW! 
@dee-y nice job, your icon design was just amazing ! 

If i would pick one a choose the second one ( colored green/orange ) and I think just for the icon the first one but with an white background (it's a wrong choose of color because isn't constraint or something like that?)

I'm so excited to start use this logo !

Thank you very much.

**Comment by dee-y** [comment]
Hi @tiago-marques, am glad you liked the logo design, i have made the changes below and made files ready for download at google drive link
https://drive.google.com/drive/folders/1QDWSR30s7mbR65fh_kc6RKhpksxFarM_?usp=sharing


![logomark1](https://user-images.githubusercontent.com/36637989/41571773-b9d8b98a-736c-11e8-813a-e57bbd3547de.png)
![logomark2](https://user-images.githubusercontent.com/36637989/41571774-badb78b8-736c-11e8-8fc2-c3b5782741c7.png)
![logomark3](https://user-images.githubusercontent.com/36637989/41571776-bbd43c64-736c-11e8-8e6f-3bc9fa47d554.png)
![logomark4](https://user-images.githubusercontent.com/36637989/41571777-bc1f918c-736c-11e8-800c-d1fca850042f.png)
![logomark5](https://user-images.githubusercontent.com/36637989/41571778-bc86d61c-736c-11e8-9b57-b15fc0a58953.png)
![logomark6](https://user-images.githubusercontent.com/36637989/41571781-bd29c6e2-736c-11e8-848e-3007463e0e69.png)
![logomark7](https://user-images.githubusercontent.com/36637989/41571783-bd9a6410-736c-11e8-8def-f3059be4dc5c.png)
![logomark8](https://user-images.githubusercontent.com/36637989/41571785-bddb4016-736c-11e8-87c9-2d27c91a3739.png)


![logotype](https://user-images.githubusercontent.com/36637989/41571436-0de891c8-736b-11e8-831a-f4d3a8b4d03c.png)


If you need any assistance you could also reach me on stevetech2012@gmail.com

**Comment by dee-y** [comment]
Loco icon with the shadows inside
![logomark1b](https://user-images.githubusercontent.com/36637989/41663876-57a61f88-749c-11e8-8095-fb84ddf6cf3c.png)
![logomark1c](https://user-images.githubusercontent.com/36637989/41663877-57f945b4-749c-11e8-9580-824ab1e9519f.png)

**Comment by tiago-marques** [comment]
@dee-y  the new logo is alive !

Thank you very much.

**Comment by dee-y** [comment]
Glad i was able to contribute to your awesome project :)
stevetech2012@gmail.com
best regards,
Dee-y.
